### ISSUE TITLE
Syntax highlighting breaks when multiline string has hyphens

### ISSUE THREAD

**Issue by stemid** [pearofducks/ansible-vim#106]
```yaml
task: >
  testing variable {{ like_this }}
  testing quoted variable '{{ like_this }}' \
  variable assignment='{{ this_is_ok }}' \
  testing variable-assignment='{{ oh_this_breaks }}'
  testing newline
args:
  wut: foobar

more_objects:
  - key: syntax_check
    value: "Verifying that Syntax highlighting works"
  - key: syntax_check02
    value: 'Verifying more quotes'
```

It only breaks when line 5 is used, must be a combination of hyphenated string values followed by quote marks without whitespace between.
