### ISSUE TITLE
Do not highlight "name" that is part of a module

### ISSUE THREAD

**Issue by savchenko** [pearofducks/ansible-vim#109]
Consider the following:
```yaml
- name: Create xfer user
  user:
    name: "{{ agent_name }}"
    shell: /bin/sh
    groups: agents
```

And here is the highlight:
![image](https://user-images.githubusercontent.com/300146/95738349-9a580280-0c78-11eb-9ae9-030c6b40c3a8.png)

I would imagine that second "name" should have the same highlight group as the "shell" and "groups".
