### ISSUE TITLE
Detect column in addition to the equality sign

### ISSUE THREAD

**Issue by savchenko** [pearofducks/ansible-vim#110]
Module parameters defined with the column sign are highlighted drastically differently.

Example:
```yaml
---
- hosts: localhost
  tasks:
    - set_fact:
        - dummy: true
        - teapot: false
    - set_fact: dummy=false, teapot=true
    - debug: msg="{{ dummy, teapot }}"
```

And here is the highlighted result:
![image](https://user-images.githubusercontent.com/300146/95742847-3c2f1d80-0c80-11eb-9d5e-1800c021d1bf.png)

Perhaps it would make sense to (optionally) allow the same highlighting style for <kbd>:</kbd> and <kbd>=</kbd> definitions?

_Edit:_ To clarify - allow column-based definitions to be dimmed the same way as equal-sign-based ones.
