### ISSUE TITLE
Strings no longer getting the "String" highlight group, but getting the "Normal" highlight group

### ISSUE THREAD

**Issue by Life5ign** [pearofducks/ansible-vim#119]
For example, "this string" gets assigned the Normal highlight group, after installing this plugin.  I would just override this, but my knowledge of how vim identifies what patterns get assigned to what highlight group is lacking.  Can this be fixed, is this just me, and is there a `.vimrc` override as a quick fix?

**Comment by pearofducks** [comment]
What highlight is used is dependent on where in YAML context the content occurs. This doesn't sound like a bug, but if you provide a bit more context I can look into it.

**Comment by Life5ign** [comment]
Thanks, here is an example:

```yaml
- name: Get information about main vst production security group and write results to a local file
  hosts: localhost
  gather_facts: False
  vars:
    boto_profile: "{{ vst_gov_boto_profile }}"
    security_group_id: "blah"
...
```
"blah" looks the same as the content after name: Get....

For me, yaml did highlight strings with the String syntax group highlight color, which I kind of miss.  What other info can I provide?
