### ISSUE TITLE
Task Parameters not highlighted differently when using YAML literal

### ISSUE THREAD

**Issue by defionscode** [pearofducks/ansible-vim#12]
Not a huge deal but when a task is written as 

```yml
  tasks:
    - name: Auth Module Example
      na_eseries_auth:
        ssid: 2·
        admin_pass: 'hello2'
        password: 'hello3'
        set_admin: no
        api_url: "{{ netapp_api_url }}"
        api_username: "{{ netapp_api_username }}"
        api_password: "{{ netapp_api_password }}"
      when: auth
```

The color of the params like `ssid`, `admin_pass`, etc are of the same color as the module name, in this example, `na_eseries_auth`
