### ISSUE TITLE
Starting a new module after  blank line does not unindent

### ISSUE THREAD

**Issue by sean-abbott** [pearofducks/ansible-vim#32]
When I'm trying to start a new module after I've finished one, this plugin always indents to the level of the previous module's keys.  i.e.:

```
- name: "ensure staged init file is populated"                                                         
  become: yes
  template:
    src: "_etc_init.d_staged_service.j2"
    dest: "/etc/init.d/{{ staged_service }}"
    owner: "root"
    group: "root"
    mode: "0755"

    - name: "this shouldn't be indented"
```
This is super frustrating.

Thanks for the great plugin!  I really generally love it!

**Comment by pearofducks** [comment]
Fair point, try this branch: https://github.com/pearofducks/ansible-vim/tree/newline-indent

**Comment by sean-abbott** [comment]
If I put two newlines between the end of a block and the beginning of a new one, it doesn't happen.  Still happens with only one newline.

Thanks!

(If it matter, ubuntu 16.04 vim: 
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
)

**Comment by pearofducks** [comment]
To clarify...

This (with a spare newline there) works:
```
- name: "ensure staged init file is populated"                                                         
  become: yes
  template:
    src: "_etc_init.d_staged_service.j2"
    dest: "/etc/init.d/{{ staged_service }}"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "this shouldn't be indented"
```
