### ISSUE TITLE
the identing breaks when commenging lines in block mode

### ISSUE THREAD

**Issue by dimovnike** [pearofducks/ansible-vim#46]
When I comment a block of lines in visual  block mode (ctrl-V, jjjj, I, then enter #) the identation jumps to right, after i hit escape - all selected lines are indented. For example take this code:

>- name: test comment
>  copy:
>    content: blabla
>    dest: somewhere
>    mode: 0666 

If u I select from first to last lines (the first column) and hit "I", enter the # and hit escape, it becomes:

>     #- name: test comment
>     #  copy:
>     #    content: blabla
>     #    dest: somewhere
>     #    mode: 0666
> 

sometimes it breaks even more, the dash character is ending up between letters. I tried with a totally clean .vimrc file and the problem is still there.

**Comment by dimovnike** [comment]
it seems that the plugin itself is not causing this, but the vimplug itself... Adding only these lines in .vimrc

> call plug#begin('~/.vim/plugged')
> call plug#end()
> 

is enough for the bug to appear. Also i remember trying different plugin systems in the past (pathogen, etc) but the problem was still there. I will close the bug since its not related to this plugin but any suggestion is appreciated.....

**Comment by kustodian** [comment]
I fixed this issue by appending `cinkeys-=0# indentkeys-=0#` to the `yaml.ansible` file type line in `~/.vimrc`, for example:
```
autocmd Filetype yaml.ansible setlocal tabstop=2 shiftwidth=2 expandtab cinkeys-=0# indentkeys-=0#
```

**Comment by porjo** [comment]
I'm having this issue. @kustodian suggested fix doesn't work for me.

My file is correctly being detected as yaml.ansible, i highlight a series of tasks then hit `=` to autoformat that block of code, it pushes each task further to the right than the one immediately above it e.g.

```
---
- name: get EC2 instances
  ec2_instance_facts:
    filters:
      "{{ { 'tag:' ~ tag_key: tag_name } }}"
  register: ec2_metadata

- name: create AMI
  ec2_ami:
    instance_id: "{{ item.instance_id }}"
    wait: no
    name: "{{ item.tags.Name + ' ' + ansible_date_time.iso8601_basic }}"
    no_reboot: yes
  loop: "{{ ec2_metadata.instances }}"
```
becomes
```
---
- name: get EC2 instances
  ec2_instance_facts:
    filters:
      "{{ { 'tag:' ~ tag_key: tag_name } }}"
      register: ec2_metadata

      - name: create AMI
        ec2_ami:
          instance_id: "{{ item.instance_id }}"
          wait: no
          name: "{{ item.tags.Name + ' ' + ansible_date_time.iso8601_basic }}"
          no_reboot: yes
          loop: "{{ ec2_metadata.instances }}"
```
