### ISSUE TITLE
breaks AutoIndent and SmartIndent

### ISSUE THREAD

**Issue by dminca** [pearofducks/ansible-vim#52]
Having the following configs in `~/.vimrc`

```vim
filetype plugin indent on
set ai
set si
```
Testing inside ansible task:

```yml
- name: deploy template
  template:
  src: foo.j2
  dest: /etc/foo
```
after hitting <kbd>ENTER</kbd> after `template:` it's not auto-indenting `src:` (and whatever comes next) with 2 spaces.

Compare this behavior between `:set filetype=yaml` and `:set filetype=ansible`
